### ISSUE TITLE
Error while tapping on one of the actions on my iPhone

### ISSUE THREAD

**Issue by septeven** [DBuit/light-popup-card#12]
Hi,
Thanks for having implemented the service call instead of the scene - this is great!

I have a problem though with my iPhone (iPhone 7+ under iOS 13.3, HA companion app, same thing if using Safari). Nothing happens when I tap on action but error in HA logs. It works like a charm on my iMac though.

Here is the error showing up in the log:  

> http:// HASSIOADRESS /community_plugin/light-popup-card/light-popup-card.js?v=20:193:30040 TypeError: undefined is not an object (evaluating 't.path[0]')

> 11:48 components/system_log/__init__.py (ERROR)
>

**Comment by DBuit** [comment]
@septeven thanks for mentioning it. it was a specific error in safari i just released new version with a fix for it!
