### ISSUE TITLE
feature request - brightness %

### ISSUE THREAD

**Issue by PostSven** [DBuit/light-popup-card#13]
Is it possible to make the brightness % dynamically move up/down when the slider bar is moved?

**Comment by septeven** [comment]
Yes, I second that, same thing for your thermostat card.
Showing the percentage in real time while sliding the slider would be a great addition ;)

**Comment by DBuit** [comment]
Will check this out woud be nice!

**Comment by DBuit** [comment]
@PostSven @septeven  i just released new version and you can now see the brightness change while sliding https://github.com/DBuit/light-popup-card/releases/tag/0.3
