### ISSUE TITLE
Bug? Light jumps to position where pressed

### ISSUE THREAD

**Issue by migo-dev** [DBuit/light-popup-card#14]
Hey man, I just discovered this and absolutely love it!
I have a horizontal stack group with 3 lights (configured via popup_cards:). When I press the middle one, it not only opens the card as intended - it also turns on the light at 28-41%.
I have tried to use another light in the middle and the behaviour is exactly the same - so it's not the light itself.

Note: I tested a little more and found out: If the brightness bar is overlapping my thumb's position on tap, it jumps to the according %.

Thanks for any help in advance.

**Comment by DBuit** [comment]
Hi @migo-dev,
So you tap on a tile and the popup opens and because you tappend on the same position the slider will appear it already changes the slider position and so the brightness gets changed? It that what is happening?

Could you make record it? than i can see how it happens and try to fix it!

**Comment by migo-dev** [comment]
Hi DBuit,

Thank you very much for your answer!

I am terribly sorry for my unclear message - yes, that's exactly what's happening. Attached you will find a screen record of it.

Thank you once again for checking this, you are a hero! :)



Von meinem Samsung Galaxy Smartphone gesendet.



-------- Ursprüngliche Nachricht --------
Von: DBuit <notifications@github.com>
Datum: 20.01.20 07:05 (GMT+01:00)
An: DBuit/light-popup-card <light-popup-card@noreply.github.com>
Cc: migo-dev <mike.buehlmann@hotmail.com>, Mention <mention@noreply.github.com>
Betreff: Re: [DBuit/light-popup-card] Bug? Light jumps to position where pressed (#14)


Hi @migo-dev<https://github.com/migo-dev>,
So you tap on a tile and the popup opens and because you tappend on the same position the slider will appear it already changes the slider position and so the brightness gets changed? It that what is happening?

Could you make record it? than i can see how it happens and try to fix it!

**Comment by DBuit** [comment]
@migo-dev in your screenrecord i looks like it opens the pop-up while pressing? or do you release the tile and does it open after releasing it?

**Comment by migo-dev** [comment]
@DBuit it seems to open when I release it. At least long presses work without opening the pop-up.

**Comment by migo-dev** [comment]
BTW: This only happens on my android. On my gf's iPhone it's working perfectly.

**Comment by DBuit** [comment]
@migo-dev are you using last version of the homekit card or do you not use that card?
You only have it when u use tap to open pop-up or also when using long press to open popup?

**Comment by migo-dev** [comment]
@DBuit No, I don't use the homekit (panel?) card, I use [vertical-in-stack-card by ofekashery](https://github.com/ofekashery/vertical-stack-in-card) (incl. picture-elements and [mini-graph-card by kalkih](https://github.com/kalkih/mini-graph-card)) for the according cards.

Just assigned the pop-up card to long press and it works perfectly - without the "ghost press" after.
