### ISSUE TITLE
Feature request - colour and styling of slider

### ISSUE THREAD

**Issue by 5and0** [DBuit/light-popup-card#15]
Is it possible to change the colour of the slider and other elements?

**Comment by DBuit** [comment]
Will make this an option in next release.

**Comment by 5and0** [comment]
Love your work. Thanks. 

In addition to matching my theme, I was thinking I would change the slider colour to match the current light colour (similar to HomeKit)

**Comment by DBuit** [comment]
@5and0 just released new version with option to change slider colors or let it be changed by the color of the light: https://github.com/DBuit/light-popup-card/releases/tag/0.3

**Comment by 5and0** [comment]
Well done... Thank you

**Comment by 5and0** [comment]
Just bought you a coffee ... really appreciate the quick response. Keep up the great work.

**Comment by septeven** [comment]
@DBuit 
Would it be possible to have the .range-holder input[type="range"] background-color customizable as well ? Thanks a lot
