### ISSUE TITLE
Icon keep "fullscreen" css even when fullscreen is set to false

### ISSUE THREAD

**Issue by jncanches** [DBuit/light-popup-card#16]
When setting the property fullscreen to false, the wrapper is correctly omitted in the HTML but the icon div keeps the fullscreen that leads to a margin-top: -64px; so the icon is not visible. That's not good I think.

Thanks :)

**Comment by DBuit** [comment]
Hi @jncanches just released new version which also removes the margin-top when setting fullscreen to false. thanks for posting the issue
