### ISSUE TITLE
Bug - Light with dimmer attribute only

### ISSUE THREAD

**Issue by Tedsterh** [DBuit/light-popup-card#20]
I have a light with just a dimmer attribute, no colour or temperature. The popup only shows a switch, unlike my colour bulbs where the popup has a slider.

**Comment by DBuit** [comment]
Hi @Tedsterh  set supportedFeaturesTreshold to 0 for this entity and it will display slider.

**Comment by Tedsterh** [comment]
I have placed that inside the popup config, but it hasn't changed anything. I still get the switch instead of the slider.

`- column: 2
                tileOnRow: 4
                entities:
                  - title: Master Bedroom
                    entities:
                      - entity: light.main_light
                        popup:
                          type: 'custom:light-popup-card'
                          scenesInARow: 4
                          brightnessWidth: 130px
                          brightnessHeight: 350px
                          switchWidth: 110px
                          switchHeight: 300px
                          supportedFeaturesTreshold: 0`

**Comment by DBuit** [comment]
@Tedsterh can you share the state in de developer tools of home assistant.
Like this:
![example](https://user-images.githubusercontent.com/17079647/74744388-70258080-5262-11ea-95f1-53fbdd814fb1.png)

**Comment by Tedsterh** [comment]
<img width="705" alt="Screenshot 2020-02-18 at 15 16 43" src="https://user-images.githubusercontent.com/56851744/74749292-d8279700-5261-11ea-9350-b059c3e1be5b.png">

**Comment by DBuit** [comment]
@Tedsterh that is strange by setting `tileHoldAnimation` to 0 it should show the brightness slider when supported_features is higher than 0.

Can you share your config as code with ``` before the code and ``` after so the indentation is kept.

**Comment by Tedsterh** [comment]
> Can you share your config as code with `before the code and` after so the indentation is kept.
I did that but it doesn't seem to display the indentations.
<img width="501" alt="Screenshot 2020-02-18 at 18 23 18" src="https://user-images.githubusercontent.com/56851744/74765630-df5b9e80-527b-11ea-8922-3880b5c2bb66.png">
This is my code for the light and popup.

**Comment by DBuit** [comment]
@Tedsterh really strange i can even get a slider for a light that does not have brightness by setting `supportedFeaturesTreshold: -1`. Are you using HACS? and latest version? or manual installation?

**Comment by Tedsterh** [comment]
I am using HACS latest version, if I set the `supportedFeaturesTreshold: -1` then I get a dimmer slider. Not sure why I don't if its set to 0 instead.
