### ISSUE TITLE
2 horizontal slider

### ISSUE THREAD

**Issue by marima84** [DBuit/light-popup-card#25]
Hi,
first of all thank you for your component, I was looking for that since long...
I have a question: is it possible to place to two different slider align horizontally in one pop up-card?
I would like to have brightness and color temperature slider in one pop up-card.

Thank you
Mark

**Comment by filikun** [comment]
This is actually a good idea, or have multiple light sliders on one popup per room. Much like this but not with the left side panel. hass-smart-home-panel-card
