### ISSUE TITLE
Making it compatible with HACS

### ISSUE THREAD

**Issue by syphernl** [DBuit/light-popup-card#3]
I'd like to implement this card in my setup but HACS doesn't like it. 
I cannot add it manually either since the "Repository Structure is not compliant".

I have tested this on my fork, it seems that `custom-light-popup-card.js` needs to be renamed to `hass-custom-light-popup-card.js` (to match the repo) and HACS allows it to be installed.

**Comment by DBuit** [comment]
Hey @syphernl i want to add HACS support in the future. but for now i renamed the file hope it works now. let me know if i can help.

**Comment by syphernl** [comment]
That was fast ;-) It worked fine in my fork so I assume it'll work fine with this as well.

The only minor issue I noticed is that HACS doesn't know whether it is `type: module` or `type: js`. I've added it as module since 95% of the cards are modules.

**Comment by DBuit** [comment]
Ok good.
Ye it is module :)

**Comment by syphernl** [comment]
Odd, it is the same as on my fork but it's failing to be added manually:
```
Jan 03 17:49:17 hass hass[46551]: 2020-01-03 17:49:17 ERROR (MainThread) [hacs.repository.plugin.DBuit.hass-custom-light-popup-card] Repostitory structure not compliant
Jan 03 17:49:17 hass hass[46551]: 2020-01-03 17:49:17 ERROR (MainThread) [hacs] Validation for DBuit/hass-custom-light-popup-card failed.
``` 

Maybe HACS is caching this somehow..

**Comment by DBuit** [comment]
That's strange i dont have hacs but will install it soon and try to fix it

**Comment by DBuit** [comment]
Hi man,

i changed the structure and it is now compatible for hacs support.
Also some new features in latest release :)
