### ISSUE TITLE
Adjusting slider causes scrolling in the background

### ISSUE THREAD

**Issue by caseyjhol** [DBuit/light-popup-card#39]
If overview has enough items that overflow is enabled, adjusting the slider changes the position on the screen (scrolls).

![ezgif-5-94e7cda71121](https://user-images.githubusercontent.com/2874325/87987680-420bcd00-ca9c-11ea-8f35-413225f9791d.gif)

**Comment by DBuit** [comment]
With the new popup dialog in Hass 0.113 this is fixed
