### ISSUE TITLE
overflow:hidden css attribute make a long scene name truncated

### ISSUE THREAD

**Issue by septeven** [DBuit/light-popup-card#4]
Hi, 
Great work here - just noticed that my "long" scene name ("concentration") was truncated because of the overflow:hidden attribute of scene name.

For now, I edited the js file in order to fix it but would you mind adding a permanent fix for this ?

Also, would be great if we can close the popup by clicking/taping in the empty space, instead of clicking on the cross icon.

Thanks

**Comment by DBuit** [comment]
Hey man,

Can you post what you edited in the js file that makes it faster to fix :)
I had feature to close the popup by clicking in the empty space on my list will add that

**Comment by septeven** [comment]
I actually just deleted the overflow:hidden attribute, line 302 (under .scene-holder .scene .name), but I'm not an expert in css, just have some basics, thus I'm not sure that it would be the best way to fix it.

Glad to know you'll add the closing feature.

Also, one last thing here, would it be possible to add a feature in order to call a script instead of a scene (I made scripts for lights that I would love to call from your popup)

**Comment by DBuit** [comment]
Are the scene names not going over each other now? can you show screenshot wonder how yours looks :)

**Comment by DBuit** [comment]
You can also close the pop-up now by clicking in open space in the new update.
I renamed the project and update structure to meet hacs requirements!

**Comment by septeven** [comment]
> Are the scene names not going over each other now? can you show screenshot wonder how yours looks :) 

See "concentratio" instead of "concentration"
<img width="270" alt="Capture d’écran 2020-01-07 à 19 01 32" src="https://user-images.githubusercontent.com/3216560/71917445-63e8d680-3180-11ea-9cda-35b991070f9a.png">


> You can also close the pop-up now by clicking in open space in the new update.
> I renamed the project and update structure to meet hacs requirements!

This is great, thanks for that.

I can see that you are going to implement the use of scripts instead of scenes, that a great news, any chance to get a rough estimation of when you can get this out ? (no pressure, just want to know if I can wait for your solution, or if I need to spend time on a temporary alternative) - Thanks again

**Comment by DBuit** [comment]
Ah i see i will remove the overflow hidden.
There is a change text while go over each other but only for really long names.
