### ISSUE TITLE
Popup not working after updating HA to version 0.113

### ISSUE THREAD

**Issue by tomerbs** [DBuit/light-popup-card#40]
Hi,
All popup cards not working after updating HA to version 0.113

**Comment by caseyjhol** [comment]
Confirmed same issue with HA v0.113.0.

```console
popup.js:20 Uncaught TypeError: Cannot read property 'close' of undefined
    at popUp (popup.js:20)
    at HTMLElement._createPopup (hammer.js:2643)
    at HTMLElement._hold (hammer.js:2643)
    at HTMLElement._handleClick (hammer.js:2643)
    at Array.<anonymous> (hammer.js:2643)
    at Manager.emit (hammer.js:2519)
    at PressRecognizer.emit (hammer.js:1923)
    at PressRecognizer.tryEmit (hammer.js:1555)
    at PressRecognizer.recognize (hammer.js:1602)
    at Manager.recognize (hammer.js:2368)

Uncaught (in promise) TypeError: Cannot read property 'substr' of undefined
    at n (app.5aafc0f2.js:43806)
    at HTMLElement.value (chunk.228a62b8fe14b50890cb.js:45547)
    at HTMLElement.value (chunk.228a62b8fe14b50890cb.js:45178)
    at HTMLElement.e.showDialog (card-mod.js:5)
    at E (app.5aafc0f2.js:41299)
```

**Comment by caseyjhol** [comment]
Seems this is most likely an issue related to https://github.com/thomasloven/lovelace-card-tools. @thomasloven has made some changes that hopefully will resolve this issue.

**Comment by UmbeMont** [comment]
Do you know if we have to update something or it will be just updated in the popuc card themselves ?
my popup are all dead too.

**Comment by DBuit** [comment]
If you guys use my homekit card, i just updated the card.
This should fix the pop-ups in that card.

**Comment by DBuit** [comment]
If you use the popup in combination with browser_mod check out the readme. because the style: part to make the popup look better is also changed.

**Comment by tomerbs** [comment]
In my setup it is still not working

**Comment by DBuit** [comment]
How do you use the light pop-up card?

**Comment by tomerbs** [comment]
I'm using it with browser_mod, in version 0.113 when i try to open the
popup nothing happend, when I roll back to version 0.112 everythin works
fine.
I even try to copy the new example from your github readme and that also
didn't worked.
Please let me know if you need somthing else to solve it.
Thanks

בתאריך יום ד׳, 29 ביולי 2020, 23:45, מאת DBuit ‏<notifications@github.com>:

**Comment by DBuit** [comment]
@tomerbs this card is Just a lovelace card. If browser_mod is not opening a pop-up check the github of browser_mod for solutions. I cant help with that

**Comment by tomerbs** [comment]
But it also dosen't work for me in lovelace, can you please send me a
working example that works in your system?
Thanks

בתאריך יום ו׳, 31 ביולי 2020, 14:31, מאת DBuit ‏<notifications@github.com>:

**Comment by tomerbs** [comment]
Works after updating broser_mod version.
Thanks.
