### ISSUE TITLE
Support for brightness_pct

### ISSUE THREAD

**Issue by jcreynolds** [DBuit/light-popup-card#41]
Certain entities, namely in my case Insteon via ISY uses brightness_pct as the attribute rather than just brightness.

**Comment by jcreynolds** [comment]
So further research shows that my entities do have a brightness attribute, however they are not exposed in the attribute list.

**Comment by DBuit** [comment]
Hi @jcreynolds,

so it works for you? or you still need the brightness_pct ?

**Comment by jcreynolds** [comment]
Sorry for late response, it still doesn't work for me.  My light entities that are insteon based from an ISY that have a brightness and brightness_pct attribute show up as a toggle switch when using the popup.
