### ISSUE TITLE
With removal of supportedFeaturesTreshold, it's not possible to force type to "switch" instead of brightness slider

### ISSUE THREAD

**Issue by caseyjhol** [DBuit/light-popup-card#42]
I'm using a cover component for my garage door opener created through ESPHome. `supported_features` is set to 11, so it's automatically making it a brightness slider. What about just adding a "type" attribute that defaults to something like "auto". If "auto", it will auto-detect the type, but you could set it to "switch" or "slider" as well.

**Comment by DBuit** [comment]
Ok i Will add option to overwrite it

**Comment by caseyjhol** [comment]
Great - thanks! Thanks for all your work on this by the way. Let me know if you need help with anything.

**Comment by DBuit** [comment]
Hi @caseyjhol 
added `displayType` to force display of slider of switch
