### ISSUE TITLE
0.4.8 overwrites system language when sliding light to off

### ISSUE THREAD

**Issue by matt8707** [DBuit/light-popup-card#43]
Release 0.4.8 seems to overwrite system language when sliding light to off. Prior versions works as expected.

Maybe relevant

`if(el) {el.dataset.value = value+"%";}`

`if(el) {el.innerText = (value == 0) ? "Off" : value + "%";}`

**Comment by DBuit** [comment]
Where did you find that code?
I use this.hass.localize(`component.light.state._.off`) to the translation for the off state in the language of the hass instalation IT is running

**Comment by matt8707** [comment]
So I think the localization is working but it happens when sliding to 0%

https://github.com/DBuit/light-popup-card/blob/8e0ad1fb23de319bd1b0bd31bf9fa07d2fe2ac42/src/light-popup-card.ts#L211

* If I open a popup with a light that is off it says 'Av'
* Turn it on to 50%
* Slide it down to 0% and it says 'Off'
* Reopen the popup and it says 'Av'

**Comment by DBuit** [comment]
when a light has a brightness of 0% it is automatically off

**Comment by matt8707** [comment]
Yeah, I get that. It's the language used that changed.

**Comment by schizophrene** [comment]
I agree with @matt8707 : 
* when a light is off, and when I open this card, status is `Éteinte` (french)
* when I light up and switch off the light inside the card, status is `Off`
* when I close this card, and reopen it, status is `Éteinte` again

So, when the card is opened, and the light switched off, locale is not taken into account.

This is not a big issue, but it would be cool to solve it !
