### ISSUE TITLE
FR: make settings button invoke a more-info window

### ISSUE THREAD

**Issue by jimz011** [DBuit/light-popup-card#50]
Hi @DBuit, HA 0.115.x broke a lot of custom-cards that could be used inside of the extraSettings of your light popup card. (like the light-entity-card and the more-info-card). These cards no longer work and I was wondering if it was possible to change the settings button to behave like a `more-info` action like a normal button would do (normal behavior is `tap_action with toggle` and `hold_action with more-info`). This way when we press settings it would just open the core more-info window.

Thanks for your hard work

**Comment by DBuit** [comment]
Old issue but as far as i know cards are working as a settingsCard
