### ISSUE TITLE
FR: Any Action on Button Press

### ISSUE THREAD

**Issue by EliotHertenstein** [DBuit/light-popup-card#61]
I love that we are able to call services in the popup, but I would also love to be able to use other actions, such as "fire-dom-event" on a button. This way, I can create multiple popups spanning out of one popup!

Thanks for the great card :)

**Comment by ASNNetworks** [comment]
While were at it: please allow data templates for service calls as well. I posted this in the media_player popup-card, but should also be included in light popup card (and other popup cards like cover and switch).

https://github.com/DBuit/media_player-popup-card/issues/11

**Comment by DBuit** [comment]
fire-dom-event added in V0.5
