### ISSUE TITLE
Setting scene overloads Hue hub

### ISSUE THREAD

**Issue by syphernl** [DBuit/light-popup-card#7]
If I click on a scene to stuff that is tied to Hue bulbs they briefly become unavailable. If I turn off the lights via the Hue app I see them being turned on again. It looks like the scene activation is being done multiple times when only clicking once.

**Comment by DBuit** [comment]
that is strange af to check that. i also use scene in combination with hue lightstrips.
Can you share you scene configuration maybe we got something different that makes it behave like that

**Comment by DBuit** [comment]
@syphernl i forgot about your issue but i found out i did get called multiple times so that is probably the problem for you.
I just updated the card and scenes do work different now so if you update check the readme scenes are now actions and the way the click works changed so no double triggers.

**Comment by syphernl** [comment]
I can confirm that this now works properly! Thanks 👍

**Comment by DBuit** [comment]
Nice!
