### ISSUE TITLE
Future: Add transition time

### ISSUE THREAD

**Issue by CookieThemes** [DBuit/light-popup-card#74]
Hi,

I would like to suggest to add transition to _setBrightness function. It works well and it's a lot of smoother for eyes. 

`
    _setBrightness(state, value) {
        this.hass.callService("homeassistant", "turn_on", {
            entity_id: state.entity_id,
            brightness: value * 2.55,
            transition: 0.5
        });
    }
`

**Comment by DBuit** [comment]
@CookieThemes nice addition, it is added as an option in v0.5.1
