### ISSUE TITLE
Can't get to more-info

### ISSUE THREAD

**Issue by jelmerkk** [DBuit/light-popup-card#76]
I'm trying to be able to access (somewhere) the more-info dialog for a light. I'm using the popup-card, so on a long press I get your (beautiful!) slider. I read that people are able to get the more-info dialogue "back" in the settings, but can't seem to find the code example. If I include an entitity in the settingsCard I'm back to square 1 because pressing it there brings me back to the pop-up... Any help is appreciated!

**Comment by DBuit** [comment]
The settings also need a card to display. check the examples on github.
