### ISSUE TITLE
Home Assistant 2021.12 brightness broken

### ISSUE THREAD

**Issue by conorlap** [DBuit/light-popup-card#77]
Hey!
I've just updated to Home Assistant 2021.12 - latest version.
Light popup card now doesn't give me option to adjust brightness for my Philips Hue devices. It just gives me an On/Off switch.

![Screenshot 2021-12-11 at 20 37 56](https://user-images.githubusercontent.com/57415184/145690929-8b981a36-447c-4032-8ec7-f1c10a4e0167.png)

Expected:
![115678922-55610700-a352-11eb-893f-1ab38bb121c4](https://user-images.githubusercontent.com/57415184/145690940-3aaf9cd4-98b5-466b-acf1-a0c221cb795b.png)

**Comment by megakid** [comment]
The `displayType` defaults to `auto` and that part it broken.

To work around until this is fixed, you can use `displayType: slider` to force the use of the dimmable slider.

**Comment by DBuit** [comment]
Fixed in v0.5.1
