### ISSUE TITLE
Popup is too small

### ISSUE THREAD

**Issue by Boogaard53** [DBuit/light-popup-card#80]
This is the size of my popup, seems a bit too small

![Overview - Home Assistant (1)](https://user-images.githubusercontent.com/87951112/151604084-7734698a-a000-4df7-afc5-f0337a0bd17c.png)

![Overview - Home Assistant](https://user-images.githubusercontent.com/87951112/151603972-5aa6a3cd-8705-430e-ac40-e0596e249afd.png)

**Comment by kernel610** [comment]
I'm also experiencing this issue on the latest release (0.5.1).

![image](https://user-images.githubusercontent.com/75233032/152048351-da163c83-4622-4379-bcd9-e76b38ebc201.png)

**Comment by MrThiemann** [comment]
I added "fullscreen: false", then it will be displayed properly.

**Comment by Boogaard53** [comment]
Yeah that fixed it! Thank you :)

**Comment by Boogaard53** [comment]
Yeah that fixed it! Thank you :)
